# -*- coding: utf-8 -*-
"""Building an LLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18FyM2qUrco3O39PwjaBOJuE-cp6DH_0U

### Basics to Start with
"""

#list the words
text = ['All that we are is the result of what we have thought',
        'To be or not to be that is the question',
        'Be yourself everyone is already taken']
text

#seperate the words
import re
re.split(r'\s', text[0])
#text[0]

#recombine
' '.join(re.split(r'\s', text[0]))

# make lower case

allwords = re.split(r'\s',' '.join(text).lower())
allwords

#create a vocabulary(lexicon)
#find the unique words

vocab = sorted( set( allwords))
print(len( allwords))
print(len( vocab))

# encoder
word2idx = {}
for i,word in enumerate(vocab):
  word2idx[word] = i

#decorder
idx2word = {}
for i,word in enumerate(vocab):
    idx2word[i]=word

# fake quotes
import numpy as np
randidx = np.random.randint(0, len(vocab),size = 10)

[idx2word[i] for i in randidx]
' '.join([idx2word[i] for i in randidx])

# peak of tokenization
text_as_int = [word2idx[word] for word in allwords]
text_as_int

# numbers back into text
for tokeni in text_as_int:
  print(f'Token:{tokeni} : {idx2word[tokeni]}')

"""###Creating functions for Dictionary"""

def encoder(text):
    words = re.split(' ', text.lower())

    return [word2idx[w] for w in words]

#my_vocab = ['to', 'be']
encoder('to be')

def decoder(indices):
    return [idx2word[i] for i in indices]

decoder([16,3])

decoder(encoder('to be'))

"""###Visualize Tokenized integers"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

alltext = ' '.join(text)
tokens = encoder(alltext)
#vocab = sorted(set(allwords))

# create a figure
_, ax = plt.subplots(1, figsize=(12, 5))

# plot the tokens
ax.plot(tokens, 'ks', markersize=12, markerfacecolor=[.7, .7, .9])
ax.set(xlabel='Word index', yticks=range(len(vocab)))
ax.grid(linestyle='--', axis='y')

# invisible axis for right-hand-side labels
ax2 = ax.twinx()
ax2.plot(tokens, alpha=0)
ax2.set(yticks=range(len(vocab)), yticklabels=vocab)

plt.show()

"""### Explore context surroundinf target tokens"""

targetWord = 'to'
targetIdx = word2idx[targetWord]

# find indices
targetLocs = np.where(np.array(allwords) == targetWord)[0]
print(f"'{targetWord}' appears at indices {targetLocs}\n\n")

# print context
for t in targetLocs:
    print(tokens[t-1:t+2])
    print(' '.join(allwords[t-1:t+2]), '\n')