# -*- coding: utf-8 -*-
"""preparing_text_for_tokenization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nd4wU0y_0T7a2KHhVWQj9Uin1eNoTA-z

## Preparing Text fot Tokenization
"""

# typical libraries...
import numpy as np

# for importing and working with texts
import requests
import re

"""#### Get the book"""

# get raw text from internet
book = requests.get('https://www.gutenberg.org/files/35/35-0.txt')

# extract just the text and have a look at it
text = book.text
print(type(text))
print(len(text))

text[:2000]

"""#### Remove unnecessery chars"""

# character strings to replace with space
strings2replace = [
    '\r\n\r\nâ\x80\x9c',  # new paragraph
    'â\x80\x9c',          # open quote
    'â\x80\x9d',          # close quote
    '\r\n',               # new line
    'â\x80\x94',          # hyphen
    'â\x80\x99',          # single apostrophe
    'â\x80\x98',          # single quote
    '_',                  # underscore, used for stressing
]

# e.g., 'â\x80\x9d'.encode('latin1').decode('utf8')

# use regular expression (re) to replace those strings with space
for str2match in strings2replace:
    regexp = re.compile(r'%s' % str2match)
    text = regexp.sub(' ', text)

# remove non-ASCII characters
text = re.sub(r'[^\x00-\x7F]+', ' ', text)

# remove numbers
text = re.sub('\d+', '', text)

# and make everything lower-case
text = text.lower()

# let's have a look!
text[:2000]

"""####Split the text"""

# split by punctuation
import string
print(string.punctuation)
puncts4re = f'[{string.punctuation}\s]+'

words = re.split(puncts4re, text)
words = [item.strip() for item in words if item.strip()]

# remove single-character words
words = [item for item in words if len(item)>1]

# let's have a look
words[:50]

"""#### Create Vocabulary"""

# create the vocab! (set of unique words)
vocab = sorted(set(words))

# convenience variables for later
nWords = len(words)
nLex = len(vocab)

print(f'{nWords} words')
print(f' {nLex} unique tokens')

word2idx = {w:i for i,w in enumerate(vocab)}
idx2word = {i:w for i,w in enumerate(vocab)}

# print out a few
for i in list(word2idx.items())[0:10000:87]:
    print(i)

"""#### Create Encode and Decoder Function"""

# encoder function (using for-loop instead of list-comp)
def encoder(words, encode_dict):

    # initialize a vector of numerical indices
    idxs = np.zeros(len(words), dtype=int)

    # loop through the words and find their token in the vocab
    for i,w in enumerate(words):
        idxs[i] = encode_dict[w]

    # return the indices!
    return idxs


# also need a decoder function
def decoder(idxs, decode_dict):
    return ' '.join([decode_dict[i] for i in idxs])

"""#### Testing and Verification"""

# test the encoder
print(encoder(['the','time','machine'],word2idx))

# test the decoder
print(decoder([1,3,10],idx2word))

# test encode-then-decode

# random start location
startidx = np.random.choice(nWords)

# sequential word indices
idxs = np.arange(startidx,startidx+10)

print('Word indices:')
print(idxs), print('')

print('The words:')
wordseq = [ words[i] for i in idxs ]
print(wordseq), print('')

print('Token indices:')
tokenseq = encoder(wordseq,word2idx)
print(tokenseq), print('')

# decode
print('Decoded text from indices:')
decoder(tokenseq,idx2word)